"""
Podcast Mastering - Modal.com Serverless Backend
AI-powered audio mastering for podcasts

Uses Cloudflare R2 for file storage (presigned URL pattern)
Deploy: modal deploy modal_app.py
Test locally: modal serve modal_app.py
"""

import modal
from datetime import datetime, timedelta
import os

# Define the Modal app
app = modal.App("podcast-mastering")

# Volume for caching Whisper models
whisper_volume = modal.Volume.from_name("whisper-models", create_if_missing=True)
WHISPER_CACHE = "/root/.cache/whisper"

# Define the container image with all dependencies
image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("libsndfile1", "ffmpeg")
    .pip_install(
        "matchering>=2.0.6",
        "fastapi>=0.109.0",
        "python-multipart>=0.0.9",
        "boto3>=1.34.0",  # For S3-compatible R2 access
        "soundfile>=0.12.0",  # For detecting source sample rate
        "requests>=2.31.0",  # For webhook notifications
        "vercel-blob>=0.1.0",  # For direct Vercel Blob uploads
        "openai-whisper>=20231117",  # For transcription
        # Loudness + post-processing chain
        "pyloudnorm>=0.1.1",       # ITU-R BS.1770 LUFS measurement
        "pedalboard>=0.9.0",       # Spotify's DSP host (compressor, limiter, EQ, gain)
        "noisereduce>=3.0.0",      # Spectral noise reduction (optional pre-stage)
        "numpy>=1.26.0",
    )
    .add_local_dir("references", "/references")  # Bake reference templates into image
)

# Loudness targets (integrated LUFS)
# Standard = Spotify spec; this is the default for the new pipeline.
LOUDNESS_TARGETS = {
    "conservative": -16.0,  # Apple Podcasts / dialog-heavy
    "standard":     -14.0,  # Spotify (default)
    "loud":         -12.0,  # Broadcast-loud (YouTube-leaning)
}

# True-peak ceiling for final limiter
TRUE_PEAK_CEILING_DB = -1.0

# Backwards-compat: map the legacy `limiter_mode` values to the new `loudness_target` values.
# Kept for one deploy cycle so in-flight requests from old clients don't break.
LEGACY_LIMITER_MODE_MAP = {
    "gentle": "conservative",
    "normal": "standard",
    "loud":   "loud",
}

# Reference templates stored permanently in the container image.
# Available instantly without downloading from R2.
#
# Each entry's `file_path` is what gets passed to Matchering. The helper
# `_pick_reference_path()` below prefers a `.wav` sibling if it exists
# (re-mastered via scripts/remaster_references.py) so we can upgrade the
# reference audio quality without changing this dict.
_REFERENCE_TEMPLATE_DEFS = [
    {
        "id": "voice-optimized",
        "name": "Recommended - Optimized for Voices",
        "description": "Professional voice-optimized preset with balanced EQ and loudness. Best for podcasts and spoken content.",
        "base_path": "/references/voice-optimized",
        "kind": "podcast",
    },
    {
        "id": "female-podcast",
        "name": "Female Voice + Full Production",
        "description": "Optimized for female voices with intro music and sound effects. Ready-to-release quality.",
        "base_path": "/references/femalepodcast",
        "kind": "podcast",
    },
    {
        "id": "male-podcast",
        "name": "Male Voice + Full Production",
        "description": "Optimized for male voices with intro music and sound effects. Ready-to-release quality.",
        "base_path": "/references/maleonlyvoicesfullproduction",
        "kind": "podcast",
    },
    {
        "id": "news-broadcast",
        "name": "News & Broadcast Style",
        "description": "Breaking news channel sound. Male & female voices with background music, intros, and full production.",
        "base_path": "/references/maleandfemalenewssounds",
        "kind": "podcast",
    },
]


def _pick_reference_path(base_path: str) -> str:
    """Prefer a re-mastered .wav next to the base path, fall back to .mp3."""
    import os
    wav = base_path + ".wav"
    mp3 = base_path + ".mp3"
    return wav if os.path.exists(wav) else mp3


def _load_manifest_templates() -> list[dict]:
    """Load extra reference presets generated by
    scripts/build_preset_library.py. Each entry in the manifest gets merged
    into REFERENCE_TEMPLATES so /templates surfaces it automatically.

    Manifest schema (per entry):
      { "id": "podcast-<slug>", "name": "...", "description": "...",
        "file": "podcast-<slug>.mp3" }
    """
    import json
    import os

    manifest_path = "/references/manifest.json"
    if not os.path.exists(manifest_path):
        return []

    try:
        with open(manifest_path) as f:
            entries = json.load(f)
    except Exception as e:
        print(f"[manifest] failed to load: {e}")
        return []

    out: list[dict] = []
    for entry in entries:
        try:
            file_name = entry["file"]
            base, _ = os.path.splitext(file_name)
            out.append({
                "id": entry["id"],
                "name": entry["name"],
                "description": entry["description"],
                "base_path": f"/references/{base}",
                # Legacy manifest entries (podcast presets) have no `kind`; default
                # to "podcast" so they don't accidentally show up in the music UI.
                "kind": entry.get("kind", "podcast"),
            })
        except (KeyError, TypeError) as e:
            print(f"[manifest] skipping malformed entry: {e}")
    return out


REFERENCE_TEMPLATES = {
    t["id"]: {
        "id": t["id"],
        "name": t["name"],
        "description": t["description"],
        "file_path": _pick_reference_path(t["base_path"]),
        "kind": t.get("kind", "podcast"),
    }
    for t in (_REFERENCE_TEMPLATE_DEFS + _load_manifest_templates())
}

# Create a volume for temporary processing (downloaded from R2)
volume = modal.Volume.from_name("podcast-mastering-files", create_if_missing=True)
VOLUME_PATH = "/data"

# Store job statuses and file metadata
job_statuses = modal.Dict.from_name("podcast-mastering-jobs", create_if_missing=True)
file_metadata = modal.Dict.from_name("podcast-mastering-file-metadata", create_if_missing=True)

# R2 Configuration - stored as Modal secrets
r2_secret = modal.Secret.from_name("r2-credentials")

# Webhook configuration for email notifications
webhook_secret = modal.Secret.from_name("webhook-credentials")

# R2 bucket details
R2_BUCKET = "podcastmaster"
R2_ACCOUNT_ID = "f9b23e1cdab559b2f158c2142dad952b"
R2_ENDPOINT = f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

# Frontend webhook URL for job completion notifications
WEBHOOK_URL = "https://freepodcastmastering.com/api/webhooks/job-complete"
BLOB_UPLOAD_URL = "https://freepodcastmastering.com/api/files/get-blob-upload-url"

# File retention period (24 hours)
FILE_RETENTION_HOURS = 24


def upload_to_vercel_blob(job_id: str, output_path: str, file_size: int):
    """
    Upload the mastered file directly to Vercel Blob for premium users.
    Returns the blob URL if successful, None otherwise.
    """
    import requests
    
    webhook_token = os.environ.get("WEBHOOK_SECRET")
    if not webhook_token:
        print(f"[BLOB] Warning: WEBHOOK_SECRET not configured, skipping blob upload for job {job_id}")
        return None
    
    try:
        # Step 1: Get blob upload credentials from frontend
        print(f"[BLOB] Requesting upload credentials for job {job_id}")
        cred_response = requests.post(
            BLOB_UPLOAD_URL,
            json={
                "jobId": job_id,
                "fileName": os.path.basename(output_path),
                "fileSize": file_size,
            },
            headers={
                "Authorization": f"Bearer {webhook_token}",
                "Content-Type": "application/json",
            },
            timeout=30,
        )
        
        if not cred_response.ok:
            print(f"[BLOB] Failed to get credentials: {cred_response.status_code} - {cred_response.text}")
            return None
        
        cred_data = cred_response.json()
        
        if not cred_data.get("shouldUpload"):
            print(f"[BLOB] Skipping upload: {cred_data.get('reason', 'unknown reason')}")
            return None
        
        blob_token = cred_data["blobToken"]
        blob_pathname = cred_data["blobPathname"]
        subscription_id = cred_data.get("subscriptionId")
        output_file_name = cred_data.get("outputFileName")
        
        # Step 2: Upload directly to Vercel Blob using their API
        print(f"[BLOB] Uploading {file_size} bytes to {blob_pathname}")
        
        with open(output_path, "rb") as f:
            # Use Vercel Blob's direct upload API
            upload_response = requests.put(
                f"https://blob.vercel-storage.com/{blob_pathname}",
                data=f,
                headers={
                    "Authorization": f"Bearer {blob_token}",
                    "Content-Type": "audio/wav",
                    "x-api-version": "7",
                    "x-content-type": "audio/wav",
                },
                timeout=600,  # 10 minute timeout for large files
            )
        
        if not upload_response.ok:
            print(f"[BLOB] Upload failed: {upload_response.status_code} - {upload_response.text}")
            return None
        
        blob_result = upload_response.json()
        blob_url = blob_result.get("url")
        
        print(f"[BLOB] Successfully uploaded to: {blob_url}")
        
        return {
            "blobUrl": blob_url,
            "blobPathname": blob_pathname,
            "subscriptionId": subscription_id,
            "outputFileName": output_file_name,
            "fileSize": file_size,
        }
        
    except Exception as e:
        print(f"[BLOB] Error uploading: {e}")
        return None


def notify_job_complete(job_id: str, status: str, output_file: str = None, blob_data: dict = None):
    """
    Notify the frontend webhook that a job has completed.
    This triggers email notification to the user and database updates.
    
    Args:
        job_id: The job identifier
        status: Job status (completed/failed)
        output_file: R2 output key (for download URL fallback)
        blob_data: If premium user, contains blobUrl, subscriptionId, etc.
    """
    import requests
    
    webhook_token = os.environ.get("WEBHOOK_SECRET")
    if not webhook_token:
        print(f"Warning: WEBHOOK_SECRET not configured, skipping notification for job {job_id}")
        return
    
    try:
        payload = {
            "jobId": job_id,
            "status": status,
            "outputFile": output_file,
        }
        
        # Include blob data if we uploaded directly to Vercel Blob
        if blob_data:
            payload["blobData"] = blob_data
        
        response = requests.post(
            WEBHOOK_URL,
            json=payload,
            headers={
                "Authorization": f"Bearer {webhook_token}",
                "Content-Type": "application/json",
            },
            timeout=30,  # Increased timeout since webhook now does less work
        )
        
        if response.ok:
            result = response.json()
            print(f"Webhook notification sent for job {job_id}: {result}")
        else:
            print(f"Webhook notification failed for job {job_id}: {response.status_code} - {response.text}")
            
    except Exception as e:
        # Don't fail the job if webhook fails - just log it
        print(f"Webhook notification error for job {job_id}: {e}")


def get_r2_client():
    """Create an S3 client configured for Cloudflare R2"""
    import boto3
    return boto3.client(
        "s3",
        endpoint_url=R2_ENDPOINT,
        aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
        region_name="auto",
    )


@app.function(image=image, secrets=[r2_secret], schedule=modal.Cron("0 0 * * *"))
def cleanup_old_files():
    """
    Scheduled function that runs every hour to clean up files older than 24 hours.
    Deletes files from R2 storage.
    """
    now = datetime.utcnow()
    cutoff = now - timedelta(hours=FILE_RETENTION_HOURS)
    
    deleted_count = 0
    checked_count = 0
    
    s3 = get_r2_client()
    
    # Check all tracked files
    files_to_delete = []
    for file_id, metadata in file_metadata.items():
        checked_count += 1
        upload_time = datetime.fromisoformat(metadata.get("uploaded_at", "2000-01-01"))
        
        if upload_time < cutoff:
            files_to_delete.append((file_id, metadata))
    
    # Delete expired files from R2
    for file_id, metadata in files_to_delete:
        try:
            # Delete uploaded files from R2
            r2_key = metadata.get("r2_key")
            if r2_key:
                try:
                    s3.delete_object(Bucket=R2_BUCKET, Key=r2_key)
                    deleted_count += 1
                except Exception as e:
                    print(f"Error deleting {r2_key} from R2: {e}")
            
            # Delete output file from R2 if exists
            output_key = metadata.get("output_r2_key")
            if output_key:
                try:
                    s3.delete_object(Bucket=R2_BUCKET, Key=output_key)
                    deleted_count += 1
                except Exception as e:
                    print(f"Error deleting {output_key} from R2: {e}")
            
            # Remove from metadata tracking
            del file_metadata[file_id]
            
            # Clean up job status if exists
            job_id = metadata.get("job_id")
            if job_id and job_id in job_statuses:
                del job_statuses[job_id]
                
        except Exception as e:
            print(f"Error cleaning up file {file_id}: {e}")
    
    print(f"Cleanup complete: checked {checked_count} files, deleted {deleted_count} expired files")
    return {"checked": checked_count, "deleted": deleted_count}


@app.function(
    image=image,
    volumes={VOLUME_PATH: volume},
    secrets=[r2_secret, webhook_secret],
    timeout=36000,  # 10 hour timeout for very long podcasts
    cpu=4,  # Use 4 CPUs for faster processing
    memory=8192,  # 8GB RAM for large audio files
)
def process_audio(
    job_id: str,
    target_r2_key: str,
    reference_source: str,
    is_template: bool = False,
    output_quality: str = "standard",      # "standard" (16-bit) or "high" (24-bit)
    loudness_target: str = "standard",     # "conservative" | "standard" | "loud"
    noise_reduction: bool = False,         # AI spectral noise reduction pre-pass
    audio_type: str = "podcast",           # "podcast" | "music" — selects polish chain
):
    """
    Mastering pipeline. Stages:
      1. Download target audio from R2
      2. (optional) Spectral noise reduction
      3. Matchering — spectral match + RMS match to reference template
      4. Post-Matchering polish: subsonic HPF, presence lift, gentle de-ess, leveling compressor
      5. LUFS measurement + makeup gain to hit the loudness target
      6. True-peak brickwall limiter at -1 dBTP
      7. Write at requested bit depth, upload to R2 (and Vercel Blob for premium)

    Loudness targets (integrated LUFS):
      conservative = -16 LUFS (Apple Podcasts / dialog-heavy)
      standard     = -14 LUFS (Spotify)  ← default
      loud         = -12 LUFS (broadcast-loud)
    """
    import os
    import numpy as np
    import soundfile as sf
    import matchering as mg
    import pyloudnorm as pyln
    from pedalboard import (
        Pedalboard, HighpassFilter, PeakFilter, Compressor, Gain, Limiter,
    )

    s3 = get_r2_client()

    # Local paths for processing
    os.makedirs(f"{VOLUME_PATH}/processing", exist_ok=True)
    target_path        = f"{VOLUME_PATH}/processing/{job_id}_target.wav"
    target_clean_path  = f"{VOLUME_PATH}/processing/{job_id}_target_clean.wav"
    reference_path     = f"{VOLUME_PATH}/processing/{job_id}_reference.wav"
    matched_path       = f"{VOLUME_PATH}/processing/{job_id}_matched.wav"
    output_path        = f"{VOLUME_PATH}/processing/{job_id}_mastered.wav"
    output_r2_key      = f"outputs/{job_id}_mastered.wav"

    # Files we created and should remove on success/failure. Reference templates
    # baked into the image are NOT in this list — never delete them.
    files_to_cleanup = [target_path, target_clean_path, matched_path, output_path]

    def update_status(progress: int, message: str):
        current = job_statuses.get(job_id, {}) or {}
        current.update({"status": "processing", "progress": progress, "message": message, "output_file": None})
        job_statuses[job_id] = current

    try:
        # ============================================================
        # Stage 0 — Download inputs
        # ============================================================
        update_status(5, "Downloading your audio...")
        s3.download_file(R2_BUCKET, target_r2_key, target_path)

        update_status(10, "Loading reference template...")
        if is_template:
            template = REFERENCE_TEMPLATES.get(reference_source)
            if not template:
                raise ValueError(f"Unknown template: {reference_source}")
            reference_path = template["file_path"]  # baked into image — don't delete
            print(f"Using built-in template: {template['name']}")
        else:
            s3.download_file(R2_BUCKET, reference_source, reference_path)
            files_to_cleanup.append(reference_path)

        # Detect original sample rate so we preserve it end-to-end
        target_info = sf.info(target_path)
        sample_rate = target_info.samplerate
        print(f"Source sample rate: {sample_rate} Hz")
        print(
            f"Settings: audio_type={audio_type}, output_quality={output_quality}, "
            f"loudness_target={loudness_target}, noise_reduction={noise_reduction}"
        )

        # ============================================================
        # Stage 1 — Optional spectral noise reduction
        # ============================================================
        matchering_input = target_path

        if noise_reduction:
            import noisereduce as nr
            update_status(18, "Removing background noise...")

            audio, sr = sf.read(target_path, always_2d=True, dtype="float32")
            # noisereduce expects (channels, samples) or (samples,)
            audio_for_nr = audio.T
            reduced = nr.reduce_noise(
                y=audio_for_nr,
                sr=sr,
                stationary=False,
                prop_decrease=0.75,
                n_fft=1024,
                time_constant_s=2.0,
            )
            audio = reduced.T

            sf.write(target_clean_path, audio, sr, subtype="FLOAT")
            matchering_input = target_clean_path
            print("Noise reduction complete")

        # ============================================================
        # Stage 2 — Matchering: spectral + RMS match to reference
        # ============================================================
        # We deliberately leave headroom (threshold=0.95) so the post-Matchering
        # chain (LUFS makeup gain + true-peak limiter) has room to work without
        # fighting Matchering's internal limiter.
        podcast_config = mg.Config(
            max_length=635_040_000,
            threshold=0.95,
        )

        def log_handler(message: str):
            print(f"Matchering: {message}")
            current = job_statuses.get(job_id, {}) or {}
            current["message"] = message
            # Map matchering's internal stages to 25..70% of the overall progress bar
            lower = message.lower()
            if "loading" in lower:
                current["progress"] = 25
            elif "analyzing" in lower:
                current["progress"] = 40
            elif "matching" in lower:
                current["progress"] = 55
            elif "limiting" in lower:
                current["progress"] = 65
            elif "saving" in lower:
                current["progress"] = 70
            job_statuses[job_id] = current

        mg.log(log_handler)

        update_status(25, "Matching reference tone & EQ...")
        # Intermediate is 24-bit so we don't lose precision before the final stage.
        mg.process(
            target=matchering_input,
            reference=reference_path,
            config=podcast_config,
            results=[mg.pcm24(matched_path)],
        )

        # ============================================================
        # Stage 3 — Post-Matchering polish + LUFS normalize + true-peak limit
        # ============================================================
        update_status(75, "Polishing tone and dynamics...")
        audio, sr = sf.read(matched_path, always_2d=True, dtype="float32")

        # pedalboard expects (channels, samples)
        audio_pb = np.ascontiguousarray(audio.T)

        # Polish chain shape depends on what we're mastering. Voice content
        # benefits from de-essing and a presence lift around 2.8 kHz; music
        # has full-spectrum content where those moves would dull cymbals,
        # harshen drums, or scoop the body of guitars/keys.
        if audio_type == "music":
            polish_chain = Pedalboard([
                HighpassFilter(cutoff_frequency_hz=25.0),                                # preserve bass; just kill subsonic
                Compressor(threshold_db=-20.0, ratio=1.6, attack_ms=20.0, release_ms=150.0),  # gentle glue, slower attack
            ])
            print("Polish chain: music (HPF + gentle glue)")
        else:
            polish_chain = Pedalboard([
                HighpassFilter(cutoff_frequency_hz=40.0),                       # remove subsonic / DC
                PeakFilter(cutoff_frequency_hz=200.0,  gain_db=-1.0, q=0.7),    # tame low-mud
                PeakFilter(cutoff_frequency_hz=2800.0, gain_db= 1.0, q=0.8),    # subtle presence
                PeakFilter(cutoff_frequency_hz=6500.0, gain_db=-2.5, q=2.5),    # gentle de-esser
                Compressor(threshold_db=-18.0, ratio=2.0, attack_ms=8.0, release_ms=100.0),  # glue + level
            ])
            print("Polish chain: podcast (HPF + EQ + de-ess + glue)")

        audio_pb = polish_chain(audio_pb, sr)
        audio = audio_pb.T  # back to (samples, channels)

        # Measure loudness
        update_status(82, "Measuring loudness...")
        meter = pyln.Meter(sr)
        try:
            current_lufs = float(meter.integrated_loudness(audio))
        except Exception:
            current_lufs = -23.0  # neutral fallback
        if not np.isfinite(current_lufs) or current_lufs < -70.0:
            current_lufs = -40.0  # very-quiet fallback

        target_lufs = LOUDNESS_TARGETS.get(loudness_target, -14.0)

        # BS.1770 integrated loudness uses relative gating — applying a big gain
        # can change which blocks are gated in/out, so single-pass "gain by
        # (target - measured)" tends to overshoot by 1-3 dB on dynamic content.
        # We iterate up to 3 times with a corrective gain to converge on target.
        # Each pass: apply remaining gain delta, run limiter, re-measure.
        audio_pb = np.ascontiguousarray(audio.T)
        applied_gain_db = 0.0
        delta_db = (target_lufs - current_lufs) + 0.3   # small overshoot for limiter loss

        for pass_idx in range(3):
            delta_db = float(np.clip(delta_db, -24.0, 24.0))
            chain = Pedalboard([
                Gain(gain_db=delta_db),
                Limiter(threshold_db=TRUE_PEAK_CEILING_DB, release_ms=100.0),
            ])
            audio_pb = chain(audio_pb, sr)
            applied_gain_db += delta_db

            # Measure after this pass
            try:
                measured = float(meter.integrated_loudness(audio_pb.T))
            except Exception:
                break
            if not np.isfinite(measured):
                break

            diff = target_lufs - measured
            print(f"  pass {pass_idx + 1}: gain {delta_db:+.2f} dB -> {measured:.2f} LUFS (target {target_lufs:.1f}, diff {diff:+.2f})")

            # Converged within 0.3 dB tolerance — good enough
            if abs(diff) < 0.3:
                break
            # Next pass corrects by the remaining diff
            delta_db = diff

        audio = audio_pb.T

        # Safety: no NaN/Inf, clamp to [-1, 1]
        audio = np.nan_to_num(audio, nan=0.0, posinf=1.0, neginf=-1.0)
        audio = np.clip(audio, -1.0, 1.0)

        update_status(88, f"Loudness set to {target_lufs:.0f} LUFS")
        print(f"Loudness: {current_lufs:.2f} LUFS source -> total gain {applied_gain_db:+.2f} dB -> target {target_lufs:.1f} LUFS")

        # ============================================================
        # Stage 4 — Write output
        # ============================================================
        update_status(92, "Writing mastered audio...")
        subtype = "PCM_24" if output_quality == "high" else "PCM_16"
        sf.write(output_path, audio, sr, subtype=subtype)
        print(f"Wrote {subtype} WAV at {sample_rate} Hz")

        # Get file size for blob upload
        output_file_size = os.path.getsize(output_path)

        # Upload result to R2 (for download URL and fallback)
        update_status(94, "Uploading mastered audio...")
        s3.upload_file(output_path, R2_BUCKET, output_r2_key)

        # Try to upload directly to Vercel Blob for premium users
        update_status(96, "Saving to cloud storage...")
        blob_data = upload_to_vercel_blob(job_id, output_path, output_file_size)
        if blob_data:
            print(f"Premium user file saved to Vercel Blob: {blob_data.get('blobUrl')}")

        # Clean up local files (skip baked-in template files)
        for path in files_to_cleanup:
            if os.path.exists(path):
                os.remove(path)

        # Update file metadata with output key
        for file_id, meta in file_metadata.items():
            if meta.get("job_id") == job_id:
                meta["output_r2_key"] = output_r2_key
                file_metadata[file_id] = meta
                break

        job_statuses[job_id] = {
            "status": "completed",
            "progress": 100,
            "message": "Mastering complete!",
            "output_file": output_r2_key,
        }

        notify_job_complete(job_id, "completed", output_r2_key, blob_data)
        return {"success": True, "output_file": output_r2_key, "blob_data": blob_data}

    except Exception as e:
        import traceback
        error_msg = str(e)
        error_traceback = traceback.format_exc()
        print(f"ERROR in process_audio: {error_msg}")
        print(f"Traceback: {error_traceback}")

        for path in files_to_cleanup:
            if os.path.exists(path):
                try:
                    os.remove(path)
                except Exception:
                    pass

        job_statuses[job_id] = {
            "status": "failed",
            "progress": 0,
            "message": f"Error: {error_msg}",
            "output_file": None,
        }
        notify_job_complete(job_id, "failed", None)
        return {"success": False, "error": error_msg, "traceback": error_traceback}


@app.function(
    image=image,
    secrets=[r2_secret],
    timeout=300,  # 5 min timeout for API calls (not processing)
)
@modal.asgi_app()
def fastapi_app():
    """FastAPI web application for the API endpoints"""
    from fastapi import FastAPI, HTTPException
    from fastapi.middleware.cors import CORSMiddleware
    from fastapi.responses import RedirectResponse
    import uuid
    
    web_app = FastAPI(title="Podcast Mastering API")
    
    web_app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],  # In production, restrict to your frontend domain
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
        expose_headers=["*"],
    )
    
    @web_app.get("/")
    async def root():
        return {"status": "healthy", "service": "Podcast Mastering API (Modal + R2)"}
    
    @web_app.get("/templates")
    async def list_templates():
        """List available reference templates. Each template carries a `kind`
        ("podcast" | "music") so the frontend can filter for the right page."""
        templates = [
            {
                "id": t["id"],
                "name": t["name"],
                "description": t["description"],
                "kind": t.get("kind", "podcast"),
            }
            for t in REFERENCE_TEMPLATES.values()
        ]
        return {"templates": templates}
    
    @web_app.get("/settings")
    async def get_settings():
        """Get available mastering settings options"""
        return {
            "output_quality": {
                "options": [
                    {"id": "standard", "name": "Standard (16-bit)", "description": "Smaller file size, great for most podcasts"},
                    {"id": "high", "name": "High Quality (24-bit)", "description": "Larger files, best for professional production"},
                ],
                "default": "standard",
            },
            "loudness_target": {
                "options": [
                    {"id": "conservative", "name": "Conservative (-16 LUFS)", "description": "Apple Podcasts spec. Dynamic, dialog-friendly."},
                    {"id": "standard",     "name": "Standard (-14 LUFS)",     "description": "Spotify spec. Recommended for most podcasts."},
                    {"id": "loud",         "name": "Loud (-12 LUFS)",         "description": "Broadcast-loud. Punchy, YouTube-leaning."},
                ],
                "default": "standard",
            },
            "noise_reduction": {
                "options": [
                    {"id": False, "name": "Off", "description": "Keep the original recording untouched."},
                    {"id": True,  "name": "On",  "description": "AI-clean background noise, hum, and room tone."},
                ],
                "default": False,
            },
            "audio_type": {
                "options": [
                    {"id": "podcast", "name": "Podcast / Voice", "description": "Spoken-word polish: HPF, gentle EQ, de-esser, voice-tuned compressor."},
                    {"id": "music",   "name": "Music / Album",   "description": "Music polish: subsonic HPF + gentle glue compression. No voice-specific EQ moves."},
                ],
                "default": "podcast",
            },
            # Kept for one deploy cycle so old clients don't break.
            # Maps to loudness_target via LEGACY_LIMITER_MODE_MAP.
            "limiter_mode": {
                "deprecated": True,
                "options": [
                    {"id": "gentle", "name": "Gentle", "description": "Deprecated — use loudness_target=conservative"},
                    {"id": "normal", "name": "Normal", "description": "Deprecated — use loudness_target=standard"},
                    {"id": "loud",   "name": "Loud",   "description": "Deprecated — use loudness_target=loud"},
                ],
                "default": "normal",
            },
        }
    
    @web_app.post("/get-upload-url")
    async def get_upload_url(filename: str, content_type: str = "audio/wav"):
        """
        Generate a presigned URL for direct upload to R2.
        Client uploads directly to R2, bypassing our server.
        """
        from datetime import datetime
        
        # Validate file extension
        allowed_extensions = {".wav", ".mp3", ".flac", ".aiff", ".ogg", ".m4a"}
        ext = "." + filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
        
        if ext not in allowed_extensions:
            raise HTTPException(
                status_code=400,
                detail=f"Invalid file type. Allowed: {', '.join(allowed_extensions)}"
            )
        
        # Generate unique file ID and R2 key
        file_id = str(uuid.uuid4())
        r2_key = f"uploads/{file_id}{ext}"
        
        # Generate presigned PUT URL (valid for 2 hours)
        s3 = get_r2_client()
        presigned_url = s3.generate_presigned_url(
            "put_object",
            Params={
                "Bucket": R2_BUCKET,
                "Key": r2_key,
                "ContentType": content_type,
            },
            ExpiresIn=7200,  # 2 hours
        )
        
        # Track file metadata
        file_metadata[file_id] = {
            "r2_key": r2_key,
            "original_name": filename,
            "uploaded_at": datetime.utcnow().isoformat(),
            "content_type": content_type,
        }
        
        return {
            "file_id": file_id,
            "upload_url": presigned_url,
            "r2_key": r2_key,
        }
    
    @web_app.post("/confirm-upload")
    async def confirm_upload(file_id: str, size: int = 0):
        """
        Confirm that a file was successfully uploaded to R2.
        Called by frontend after direct R2 upload completes.
        """
        metadata = file_metadata.get(file_id)
        if not metadata:
            raise HTTPException(status_code=404, detail="File not found")
        
        # Verify file exists in R2
        s3 = get_r2_client()
        try:
            response = s3.head_object(Bucket=R2_BUCKET, Key=metadata["r2_key"])
            actual_size = response.get("ContentLength", 0)
        except Exception:
            raise HTTPException(status_code=404, detail="File not found in storage")
        
        # Update metadata with confirmed size
        metadata["size"] = actual_size
        metadata["confirmed"] = True
        file_metadata[file_id] = metadata
        
        return {
            "file_id": file_id,
            "size": actual_size,
            "status": "confirmed",
        }
    
    @web_app.post("/master")
    async def start_mastering(
        target_file_id: str,
        template_id: str = None,
        reference_file_id: str = None,
        output_quality: str = "standard",     # "standard" (16-bit) | "high" (24-bit)
        loudness_target: str = None,          # "conservative" | "standard" | "loud"
        noise_reduction: bool = False,        # AI noise-reduction pre-pass
        audio_type: str = "podcast",          # "podcast" | "music" — selects polish chain
        limiter_mode: str = None,             # DEPRECATED — kept for one deploy cycle
    ):
        """
        Start the mastering process.

        Either template_id OR reference_file_id must be provided:
        - template_id: Use a built-in reference template (faster, no upload needed)
        - reference_file_id: Use a user-uploaded reference file

        Settings:
        - output_quality:  "standard" (16-bit) or "high" (24-bit)
        - loudness_target: "conservative" (-16 LUFS), "standard" (-14 LUFS, default), "loud" (-12 LUFS)
        - noise_reduction: bool — apply AI spectral noise reduction before mastering
        - limiter_mode:    DEPRECATED. If provided and loudness_target is not, it's
                           mapped via LEGACY_LIMITER_MODE_MAP.
        """
        # Validate input - need either template or uploaded reference
        if not template_id and not reference_file_id:
            raise HTTPException(
                status_code=400,
                detail="Either template_id or reference_file_id must be provided"
            )

        # Resolve loudness_target (with legacy fallback)
        if loudness_target is None and limiter_mode is not None:
            loudness_target = LEGACY_LIMITER_MODE_MAP.get(limiter_mode, "standard")
        if loudness_target not in LOUDNESS_TARGETS:
            loudness_target = "standard"

        # Validate output_quality
        if output_quality not in ["standard", "high"]:
            output_quality = "standard"

        # Validate audio_type (selects the polish chain shape)
        if audio_type not in ["podcast", "music"]:
            audio_type = "podcast"

        # Coerce noise_reduction to bool (FastAPI usually handles this, but be defensive)
        noise_reduction = bool(noise_reduction) if noise_reduction is not None else False

        # Get target file metadata
        target_meta = file_metadata.get(target_file_id)
        if not target_meta:
            raise HTTPException(status_code=404, detail="Target file not found")

        target_r2_key = target_meta.get("r2_key")
        if not target_r2_key:
            raise HTTPException(status_code=400, detail="Target file not properly uploaded")

        # Determine reference source
        if template_id:
            if template_id not in REFERENCE_TEMPLATES:
                raise HTTPException(status_code=404, detail=f"Template '{template_id}' not found")
            reference_source = template_id
            is_template = True
        else:
            reference_meta = file_metadata.get(reference_file_id)
            if not reference_meta:
                raise HTTPException(status_code=404, detail="Reference file not found")
            reference_source = reference_meta.get("r2_key")
            if not reference_source:
                raise HTTPException(status_code=400, detail="Reference file not properly uploaded")
            is_template = False

        # Create job
        job_id = str(uuid.uuid4())

        # Update metadata with job_id for cleanup tracking
        target_meta["job_id"] = job_id
        file_metadata[target_file_id] = target_meta

        # Initialize job status
        job_statuses[job_id] = {
            "status": "pending",
            "progress": 0,
            "message": "Queued for processing...",
            "output_file": None,
        }

        # Spawn the processing function with all settings
        process_audio.spawn(
            job_id,
            target_r2_key,
            reference_source,
            is_template,
            output_quality,
            loudness_target,
            noise_reduction,
            audio_type,
        )

        return {"job_id": job_id, "message": "Mastering job started"}
    
    @web_app.get("/status/{job_id}")
    async def get_status(job_id: str):
        """Get job status"""
        status = job_statuses.get(job_id)
        if not status:
            raise HTTPException(status_code=404, detail="Job not found")
        
        return {
            "job_id": job_id,
            **status,
        }
    
    @web_app.get("/download/{job_id}")
    async def download_result(job_id: str):
        """Get a presigned download URL for the mastered audio"""
        status = job_statuses.get(job_id)
        if not status:
            raise HTTPException(status_code=404, detail="Job not found")
        
        if status["status"] != "completed":
            raise HTTPException(status_code=400, detail="Job not completed yet")
        
        output_r2_key = status.get("output_file")
        if not output_r2_key:
            raise HTTPException(status_code=404, detail="Output file not found")
        
        # Generate presigned download URL (valid for 1 hour)
        s3 = get_r2_client()
        presigned_url = s3.generate_presigned_url(
            "get_object",
            Params={
                "Bucket": R2_BUCKET,
                "Key": output_r2_key,
                "ResponseContentDisposition": f"attachment; filename=mastered_podcast.wav",
            },
            ExpiresIn=3600,  # 1 hour
        )
        
        # Redirect to the presigned URL for direct download from R2
        return RedirectResponse(url=presigned_url, status_code=302)
    
    @web_app.post("/transcribe")
    async def start_transcription(audio_r2_key: str):
        """
        Start transcription job for video captions
        """
        from datetime import datetime
        import uuid
        
        job_id = str(uuid.uuid4())
        
        # Initialize transcription status
        transcription_jobs[job_id] = {
            "status": "processing",
            "progress": 0,
            "segments": None,
            "text": None,
            "started_at": datetime.utcnow().isoformat(),
        }
        
        # Spawn transcription
        transcribe_audio.spawn(audio_r2_key, job_id)
        
        return {
            "job_id": job_id,
            "status": "processing",
            "message": "Transcription started",
        }
    
    @web_app.get("/transcribe/{job_id}")
    async def get_transcription_status(job_id: str):
        """Get transcription status and results"""
        status = transcription_jobs.get(job_id)
        if not status:
            raise HTTPException(status_code=404, detail="Transcription job not found")
        
        return {
            "job_id": job_id,
            **status,
        }
    
    return web_app


# Transcription jobs storage
transcription_jobs = modal.Dict.from_name("podcast-transcription-jobs", create_if_missing=True)

# Pre-download Whisper model to volume
@app.function(
    image=image,
    timeout=300,
    volumes={WHISPER_CACHE: whisper_volume},
)
def setup_whisper():
    """Pre-download Whisper model to cached volume"""
    import os
    os.makedirs(WHISPER_CACHE, exist_ok=True)
    model = get_whisper_model()
    print(f"Whisper model cached at {WHISPER_CACHE}")
    return {"status": "ready", "model": "base", "cache_path": WHISPER_CACHE}

# Cached Whisper model
whisper_model = None

def get_whisper_model():
    """Get or load cached Whisper model"""
    global whisper_model
    if whisper_model is None:
        import whisper
        import os
        # Ensure cache directory exists
        os.makedirs(WHISPER_CACHE, exist_ok=True)
        # Load model (will download to cache if not present)
        whisper_model = whisper.load_model("base", download_root=WHISPER_CACHE)
    return whisper_model

# Transcription function
@app.function(
    image=image,
    secrets=[r2_secret],
    timeout=600,
    cpu=2,
    memory=4096,
    volumes={WHISPER_CACHE: whisper_volume},
)
def transcribe_audio(audio_r2_key: str, job_id: str):
    """
    Transcribe audio using Whisper (called via spawn)
    Model is cached in Modal Volume for fast subsequent loads
    """
    try:
        import tempfile
        import os
        from datetime import datetime
        
        s3 = get_r2_client()
        
        # Create temp directory
        temp_dir = tempfile.mkdtemp()
        local_path = os.path.join(temp_dir, "audio.wav")
        
        # Update status
        transcription_jobs[job_id] = {
            **transcription_jobs.get(job_id, {}),
            "progress": 10,
            "message": "Downloading audio...",
        }
        
        # Download audio
        s3.download_file(R2_BUCKET, audio_r2_key, local_path)
        
        # Update status
        transcription_jobs[job_id] = {
            **transcription_jobs.get(job_id, {}),
            "progress": 30,
            "message": "Loading AI model...",
        }
        
        # Load Whisper model (cached)
        model = get_whisper_model()
        
        # Update status
        transcription_jobs[job_id] = {
            **transcription_jobs.get(job_id, {}),
            "progress": 50,
            "message": "Transcribing with AI...",
        }
        
        # Transcribe
        result = model.transcribe(
            local_path,
            language="en",
            verbose=False,
        )
        
        # Format segments
        segments = []
        for segment in result["segments"]:
            segments.append({
                "id": segment["id"],
                "start": segment["start"],
                "end": segment["end"],
                "text": segment["text"].strip(),
            })
        
        # Cleanup
        os.remove(local_path)
        os.rmdir(temp_dir)
        
        # Update final status
        transcription_jobs[job_id] = {
            "status": "completed",
            "progress": 100,
            "segments": segments,
            "text": result["text"],
            "completed_at": datetime.utcnow().isoformat(),
        }
        
        print(f"[Transcription] Job {job_id} complete: {len(segments)} segments")
        
    except Exception as e:
        import traceback
        error_msg = str(e)
        print(f"[Transcription] Error in job {job_id}: {error_msg}")
        print(traceback.format_exc())
        
        transcription_jobs[job_id] = {
            "status": "failed",
            "progress": 0,
            "error": error_msg,
        }
